version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env.dev
    ports:
      - "8080:80"
    depends_on:
      - db

  alembic:
    build:
      context: .
      dockerfile: DockerfileAlembic
    env_file:
      - .env.dev
    depends_on:
      - db

  tdata:
    build:
      context: .
      dockerfile: DockerfileTdata
    env_file:
      - .env.dev
    depends_on:
      - db
      - alembic

  gptdata:
    build:
      context: .
      dockerfile: DockerfileGPTdata
    env_file:
      - .env.dev
    depends_on:
      - db
      - alembic

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - tdata

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"
    depends_on:
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: DockerfileCelerySubscription
    env_file:
      - .env.dev
    depends_on:
      - rabbitmq

  celery2:
    build:
      context: .
      dockerfile: DockerfileCeleryNewsCollection
    env_file:
      - .env.dev
    depends_on:
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: DockerfileFlower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
      - celery2

  bot_app:
    build:
      context: .
      dockerfile: DockerfileBotApp
    env_file:
      - .env.dev
    depends_on:
      - db
      - alembic
      - tdata
      - rabbitmq
      - celery
      - celery2

  subscription_service:
    build:
      context: .
      dockerfile: DockerfileSubscriptionService
    env_file:
      - .env.dev
    depends_on:
      - bot_app

  news_collection_service:
    build:
      context: .
      dockerfile: DockerfileNewsCollectionService
    env_file:
      - .env.dev

  summary_service:
    build:
      context: .
      dockerfile: DockerfileSummaryService
    env_file:
      - .env.dev
    depends_on:
      - news_collection_service

  digest_service:
    build:
      context: .
      dockerfile: DockerfileDigestService
    env_file:
      - .env.dev
    depends_on:
      - bot_app
      - subscription_service
      - news_collection_service

volumes:
  postgres_data:
