"""fix: Role

Revision ID: 00be06b53b46
Revises: 7ed5266c2f2d
Create Date: 2023-07-18 18:21:55.998612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00be06b53b46'
down_revision = '7ed5266c2f2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    op.add_column('roles', sa.Column('gpt_system_content', sa.String(), nullable=False))
    op.add_column('roles', sa.Column('gpt_user_content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'gpt_user_content')
    op.drop_column('roles', 'gpt_system_content')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
