"""add another Time for posts

Revision ID: 0d57ab28c71f
Revises: 798864024f50
Create Date: 2023-08-13 00:06:31.790932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d57ab28c71f'
down_revision = '798864024f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('processed_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'processed_date')
    # ### end Alembic commands ###
