"""Fix

Revision ID: 11d40df04227
Revises: 7b34b60603ea
Create Date: 2023-07-19 16:25:58.221374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d40df04227'
down_revision = '7b34b60603ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
