"""small fix

Revision ID: 278c443fec0d
Revises: 8d27dafd3e22
Create Date: 2023-07-19 15:55:38.039936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278c443fec0d'
down_revision = '8d27dafd3e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
