"""remove role,intonation

Revision ID: 2b24775f5c44
Revises: 5dcee4ce2b91
Create Date: 2023-07-18 16:01:11.265020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b24775f5c44'
down_revision = '5dcee4ce2b91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'role')
    op.drop_column('user_settings', 'intonation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('intonation', postgresql.ENUM('OFFICIAL', 'COMEDY_SARCASTIC', name='intonationenum'), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('role', postgresql.ENUM('ANNOUNCER', name='roleenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
