"""add summaries

Revision ID: 493a154e6c48
Revises: e9335a983d71
Create Date: 2023-07-18 16:16:57.314135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493a154e6c48'
down_revision = 'e9335a983d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    # ### end Alembic commands ###
