"""test

Revision ID: 4f6160e4dc2d
Revises: e7bbe865a8f2
Create Date: 2023-07-08 21:39:52.530246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6160e4dc2d'
down_revision = 'e7bbe865a8f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
