"""change schedule

Revision ID: 5dcee4ce2b91
Revises: 0d6c35b70afd
Create Date: 2023-07-16 20:21:42.978053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcee4ce2b91'
down_revision = '0d6c35b70afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beat_schedule', sa.Column('task_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beat_schedule', 'task_name')
    # ### end Alembic commands ###
