"""change one-to-one digests for users

Revision ID: 69edb6535250
Revises: aabfb37f37e3
Create Date: 2023-08-15 15:30:40.091088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69edb6535250'
down_revision = 'aabfb37f37e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'digests', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digests', type_='unique')
    # ### end Alembic commands ###
