"""add cascade delete to channel

Revision ID: 7158cd2ff0ea
Revises: 92f39eb2e1d8
Create Date: 2023-06-21 16:57:49.491050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7158cd2ff0ea'
down_revision = '92f39eb2e1d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
