"""add user settings

Revision ID: 73d8c63f50a5
Revises: 4f6160e4dc2d
Create Date: 2023-07-16 01:18:34.772035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d8c63f50a5'
down_revision = '4f6160e4dc2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('periodicity', sa.Enum('HOURLY', 'EVERY_THREE_HOURS', 'EVERY_SIX_HOURS', 'FOR_TEST', name='periodicityenum'), nullable=True),
    sa.Column('role', sa.Enum('ANNOUNCER', name='roleenum'), nullable=True),
    sa.Column('intonation', sa.Enum('OFFICIAL', 'COMEDY_SARCASTIC', name='intonationenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
