"""Fix

Revision ID: 783df719bc14
Revises: faddec4e5ccf
Create Date: 2023-07-25 02:31:57.987394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783df719bc14'
down_revision = 'faddec4e5ccf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
