"""AdminUser add role

Revision ID: 792d7731ecdd
Revises: 892bf59c1527
Create Date: 2023-09-05 05:42:55.795080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792d7731ecdd'
down_revision = '892bf59c1527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('role', sa.String(), nullable=False, server_default="ADMINISTRATOR"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'role')
    # ### end Alembic commands ###
