"""add Time for disabled users

Revision ID: 798864024f50
Revises: 0dbce063f9fd
Create Date: 2023-08-11 00:12:14.144889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798864024f50'
down_revision = '0dbce063f9fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_post_id_key', 'posts', type_='unique')
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled_at')
    op.create_unique_constraint('posts_post_id_key', 'posts', ['post_id'])
    # ### end Alembic commands ###
