"""add Digest m2m

Revision ID: 79fcc8a891de
Revises: 7158cd2ff0ea
Create Date: 2023-06-23 02:06:22.891555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fcc8a891de'
down_revision = '7158cd2ff0ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('generation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digests_posts',
    sa.Column('digest_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digests_posts')
    op.drop_table('digests')
    # ### end Alembic commands ###
