"""CategoryAssociation

Revision ID: 7e083d860192
Revises: 792d7731ecdd
Create Date: 2023-09-06 05:47:26.491947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e083d860192'
down_revision = '792d7731ecdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_categories', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_categories', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
