"""fix: Summary

Revision ID: 7ed5266c2f2d
Revises: ef84d1b76d1d
Create Date: 2023-07-18 17:09:30.788423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed5266c2f2d'
down_revision = 'ef84d1b76d1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('content', sa.String(), nullable=False))
    op.add_column('summaries', sa.Column('for_role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'for_role')
    op.drop_column('summaries', 'content')
    # ### end Alembic commands ###
