"""some changes to user settings

Revision ID: 827df158d60a
Revises: 73d8c63f50a5
Create Date: 2023-07-16 01:35:03.508502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827df158d60a'
down_revision = '73d8c63f50a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
