"""fix Channel

Revision ID: 8498570ecf0f
Revises: ba7ae3f3a896
Create Date: 2023-06-20 22:15:41.168122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8498570ecf0f'
down_revision = 'ba7ae3f3a896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_user_id_fkey', 'channels', type_='foreignkey')
    op.drop_column('channels', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('channels_user_id_fkey', 'channels', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
