"""Add role_id and intonation_id to digests

Revision ID: 854b1791c62c
Revises: 059e9f243f3d
Create Date: 2023-07-30 00:48:15.832960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854b1791c62c'
down_revision = '059e9f243f3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('digests', sa.Column('intonation_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'intonation_id')
    op.drop_column('digests', 'role_id')
    # ### end Alembic commands ###
