"""redo connection of telegram channels and telegram users

Revision ID: 86058e0ed68d
Revises: eac6de98fd69
Create Date: 2023-07-18 01:13:16.368685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86058e0ed68d'
down_revision = 'eac6de98fd69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.account_id'], name='telegram_channels_account_id_fkey'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], name='telegram_channels_channel_id_fkey'),
    sa.PrimaryKeyConstraint('account_id', 'channel_id', name='telegram_channels_pkey')
    )
    # ### end Alembic commands ###
