"""add users_categories

Revision ID: 892bf59c1527
Revises: a8d1597c4783
Create Date: 2023-09-05 02:33:05.229523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892bf59c1527'
down_revision = '36fb1f5cbd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_categories',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
