"""mod Digest

Revision ID: 8bd3254cdf38
Revises: 87395a65ffff
Create Date: 2023-06-29 03:36:22.346787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd3254cdf38'
down_revision = '87395a65ffff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('digests_posts', 'digest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('digests_posts', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('digests_posts', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('digests_posts', 'digest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
