"""add email field to user

Revision ID: 90a0e898d0eb
Revises: 7e083d860192
Create Date: 2023-09-18 06:28:19.681177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a0e898d0eb'
down_revision = '7e083d860192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('digests_user_id_key', 'digests', type_='unique')
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.create_unique_constraint('digests_user_id_key', 'digests', ['user_id'])
    # ### end Alembic commands ###
