"""add is_active for digests

Revision ID: aabfb37f37e3
Revises: 0d57ab28c71f
Create Date: 2023-08-14 08:08:25.424769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabfb37f37e3'
down_revision = '0d57ab28c71f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'is_active')
    # ### end Alembic commands ###
