"""update-1

Revision ID: ba7ae3f3a896
Revises: 00c0de59b187
Create Date: 2023-06-16 19:42:24.496368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7ae3f3a896'
down_revision = '00c0de59b187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint(None, 'posts', ['post_id'])
    op.drop_column('posts', 'post_url')
    op.add_column('telegram_accounts', sa.Column('session_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_accounts', 'session_string')
    op.add_column('posts', sa.Column('post_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'user_id')
    # ### end Alembic commands ###
