"""change one-to-one digests for users

Revision ID: c9466a1846e6
Revises: aabfb37f37e3
Create Date: 2023-08-15 15:16:18.440304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9466a1846e6'
down_revision = 'aabfb37f37e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'digests', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digests', type_='unique')
    # ### end Alembic commands ###
