"""add role

Revision ID: ce55dc2bef78
Revises: 2b24775f5c44
Create Date: 2023-07-18 16:12:39.945205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce55dc2bef78'
down_revision = '2b24775f5c44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_settings', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_settings', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
