"""Remove total summary from digest

Revision ID: d4bf221470ea
Revises: d770eba2cbb2
Create Date: 2023-07-18 23:22:28.191634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bf221470ea'
down_revision = 'd770eba2cbb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'total_summary')
    op.create_unique_constraint(None, 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.add_column('digests', sa.Column('total_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
