"""add total_summary

Revision ID: e7bbe865a8f2
Revises: 8bd3254cdf38
Create Date: 2023-07-08 12:30:46.826236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bbe865a8f2'
down_revision = '8bd3254cdf38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('total_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'total_summary')
    # ### end Alembic commands ###
