"""fix

Revision ID: ef84d1b76d1d
Revises: 86058e0ed68d
Create Date: 2023-07-18 01:27:22.116934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef84d1b76d1d'
down_revision = '86058e0ed68d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('account_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'channels', 'telegram_accounts', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'account_id')
    # ### end Alembic commands ###
