"""remove unique digest.user_id

Revision ID: fdd149dff793
Revises: a8d1597c4783
Create Date: 2023-09-05 02:11:10.438195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd149dff793'
down_revision = 'a8d1597c4783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'digests', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digests', type_='unique')
    # ### end Alembic commands ###
